### ISSUE TITLE
Document site-specific username format

### ISSUE THREAD

**Issue by pjz** [SpaceApi-archive/SchemaValidator#2]
For sites like twitter and facebook, where your name is unique, does the API expect just handles, like `@NovaLabs`? or a full URL?  It matters most for anyone wanting to consume the API, I suppose, but I was also a bit confused when filling it out, though I defaulted to a URL because I figured that was easily detectable.

**Comment by slopjong** [comment]
Good question, I don't know. The documentation lacks this information.

I suggest to have a look at the spaces which have implemented the facebook field and use the convention most of them used. A list of these spaces is available on [spaceapi.net/documentation](http://spaceapi.net/documentation). Click on _Filters_ on the left, scroll down to the filters overview and click on `contact.facebook`.

**Comment by pjz** [comment]
Hrm. A quick census shows 7 of 24 use raw usernames for facebook while everyone else uses a URL.  So should I make you a PR that fixes the doc in 0.13 and 0.14-draft? or just 0.14-draft ?

**Comment by slopjong** [comment]
I hoped it was the opposite. On the other side the full URL allows a simple copy & paste. Do you think we should go for the full URL, also for twitter?

Please edit both, 0.13 and the draft. They don't differ as of now or at least they shouldn't. As long as there are no changes made to the structure I continue to maintain 0.13 because 0.14 isn't linked anywhere yet if I remember correctly.
